/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import Repositorio.RepAluno;
import javax.swing.JOptionPane;
import model.Aluno;


/**
 *
 * @author ESCOLA
 */
public class JDAluno extends javax.swing.JDialog {

    /**
     * Creates new form JDAluno
     */
    public JDAluno(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldnome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldcpf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldtelefone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldendereco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldbairro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldnumero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldcidade = new javax.swing.JTextField();
        jButtoncadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
        getContentPane().add(jTextFieldid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel2.setText("nome");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));
        getContentPane().add(jTextFieldnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 150, 20));

        jLabel3.setText("CPF");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        getContentPane().add(jTextFieldcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, 20));

        jLabel4.setText("Telefone");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));
        getContentPane().add(jTextFieldtelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 140, 20));

        jLabel5.setText("endereco");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jTextFieldendereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldenderecoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldendereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 180, 20));

        jLabel6.setText("bairro");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));
        getContentPane().add(jTextFieldbairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 150, -1));

        jLabel7.setText("numero");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jTextFieldnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnumeroActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 150, 20));

        jLabel8.setText("cidade");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        jTextFieldcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldcidadeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldcidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 120, 20));

        jButtoncadastrar.setText("cadastrar");
        jButtoncadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtoncadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldenderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldenderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldenderecoActionPerformed

    private void jTextFieldcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldcidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldcidadeActionPerformed

    private void jTextFieldnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnumeroActionPerformed

    private void jButtoncadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncadastrarActionPerformed
    Aluno aluno = new Aluno();
    
    if(!jTextFieldid.getText().equals("")){
    aluno.setId(Integer.parseInt(jTextFieldid.getText()));
    }
    
    aluno.setNome(jTextFieldnome.getText());
    aluno.setCpf(jTextFieldcpf.getText());
    aluno.setTelefone(jTextFieldtelefone.getText());
    aluno.setEndereco(jTextFieldendereco.getText());
    aluno.setBairro(jTextFieldbairro.getText());
    aluno.setNumero(jTextFieldnumero.getText());
    aluno.setCidade(jTextFieldcidade.getText());
    
    RepAluno repAluno = new RepAluno();
    repAluno.inserir(aluno);
    JOptionPane.showMessageDialog(null , "Cadastrado com sucesso.");

    }//GEN-LAST:event_jButtoncadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDAluno dialog = new JDAluno(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtoncadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextFieldbairro;
    private javax.swing.JTextField jTextFieldcidade;
    private javax.swing.JTextField jTextFieldcpf;
    private javax.swing.JTextField jTextFieldendereco;
    private javax.swing.JTextField jTextFieldid;
    private javax.swing.JTextField jTextFieldnome;
    private javax.swing.JTextField jTextFieldnumero;
    private javax.swing.JTextField jTextFieldtelefone;
    // End of variables declaration//GEN-END:variables




}
